### ISSUE TITLE
Scheduling packet handling fails because packet buffer is deallocated by then

### ISSUE THREAD

**Issue by mdashlw** [HypixelDev/ForgeModAPI#4]
Packet buffer is reference counted and is already deallocated by the next tick
```java
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1187) ~[AbstractByteBuf.class:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1170) ~[AbstractByteBuf.class:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570) ~[AbstractByteBuf.class:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:579) ~[AbstractByteBuf.class:4.0.23.Final]
	at net.minecraft.network.PacketBuffer.readBoolean(SourceFile:604) ~[em.class:?]
	at net.hypixel.modapi.serializer.PacketSerializer.readBoolean(PacketSerializer.java:25) ~[PacketSerializer.class:?]
	at net.hypixel.modapi.HypixelModAPI.handle(HypixelModAPI.java:123) ~[HypixelModAPI.class:?]
```
Using `retain` and `release` like this fixes the issue:
```java
            packet.getBufferData().retain();
            Minecraft.getMinecraft().addScheduledTask(() -> {
                try {
                    HypixelModAPI.getInstance().handle(identifier, new PacketSerializer(packet.getBufferData()));
                } catch (Exception e) {
                    LOGGER.warn("Failed to handle packet " + identifier, e);
                } finally {
                    packet.getBufferData().release();
                }
            });
```

**Comment by ConnorLinfoot** [comment]
Fixed with https://github.com/HypixelDev/ForgeModAPI/commit/8985789d26a492efad92f39c5ee8d79198666ceb
